name: Build

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if artifact is from a different repo
          # Required, workflow file name or ID
          workflow: variables.yaml
          workflow_conclusion: success
          name: github-env
          # Optional, directory where to extract artifact. Defaults to the artifact name (see `name` input)
          path: .github
      - name: Variables
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .github/.env
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: echo 1